"""
Test script to verify word-to-phoneme alignment fix.

This tests the prepare_pronunciation_widget_data function with the
problematic example "The quick brown fox jumps over the lazy dog."
"""

import sys
sys.path.insert(0, "c:\\Users\\f0per\\f28\\Accent-Coach-AI")

from app import generate_reference_phonemes, prepare_pronunciation_widget_data


def test_alignment():
    """Test the quick brown fox example."""
    reference_text = "The quick brown fox jumps over the lazy dog."

    print("=" * 70)
    print("Testing Word-to-Phoneme Alignment")
    print("=" * 70)
    print(f"\nInput text: {reference_text}\n")

    # Generate phonemes using gruut
    lexicon, words = generate_reference_phonemes(reference_text, lang="en-us")

    print("Lexicon generated by gruut:")
    print("-" * 70)
    for word, phonemes in lexicon:
        print(f"  {word:12} → /{phonemes}/")
    print()

    # Prepare widget data
    widget_data = prepare_pronunciation_widget_data(reference_text, lexicon)

    print("Widget data prepared:")
    print("-" * 70)
    print(f"Total phoneme string: /{widget_data['phoneme_text']}/")
    print()

    print("Word timings (word → phonemes mapping):")
    print("-" * 70)
    for wt in widget_data["word_timings"]:
        print(f"  {wt['word']:12} → /{wt['phonemes']}/")
    print()

    # Verify alignment
    print("Verification:")
    print("-" * 70)
    assert len(widget_data["word_timings"]) == len(words), \
        f"Mismatch: {len(widget_data['word_timings'])} word_timings vs {len(words)} words"

    for i, (wt, (expected_word, expected_phon)) in enumerate(zip(widget_data["word_timings"], lexicon)):
        assert wt["word"] == expected_word, \
            f"Word mismatch at index {i}: {wt['word']} != {expected_word}"
        assert wt["phonemes"] == expected_phon, \
            f"Phoneme mismatch at index {i}: {wt['phonemes']} != {expected_phon}"

    print("✓ All word-to-phoneme mappings are correct!")
    print("✓ Alignment preserved correctly!")
    print()

    print("=" * 70)
    print("SUCCESS: Word-phoneme alignment working correctly!")
    print("=" * 70)


if __name__ == "__main__":
    test_alignment()
