"""
Simple test script to verify word-to-phoneme alignment logic.

This isolates just the alignment logic without importing the full app.
"""

import sys
import io

# Fix encoding for Windows console
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from gruut import sentences
from phonemizer.punctuation import Punctuation
from typing import List, Tuple


def generate_reference_phonemes(text: str, lang: str = "en-us") -> Tuple[List[Tuple[str, str]], List[str]]:
    """Generate reference phonemes from text using gruut"""
    clean = Punctuation(";:,.!\"?()").remove(text)
    lexicon, words = [], []

    for sent in sentences(clean, lang=lang):
        for w in sent:
            t = w.text.strip().lower()
            if not t:
                continue
            words.append(t)
            try:
                phon = " ".join(w.phonemes)
            except:
                phon = t
            lexicon.append((t, phon))

    return lexicon, words


def prepare_pronunciation_widget_data(reference_text: str, lexicon: List[Tuple[str, str]]):
    """
    Prepare data for pronunciation widget with proper word-to-phoneme alignment.
    """
    word_timings = []
    all_phonemes = []

    for word, phonemes in lexicon:
        # Store word-level mapping for widget
        word_timings.append({
            "word": word,
            "phonemes": phonemes,
            "start": None,
            "end": None
        })

        # Collect all phonemes for backward compatibility
        all_phonemes.append(phonemes)

    return {
        "phoneme_text": " ".join(all_phonemes),
        "word_timings": word_timings
    }


def test_alignment():
    """Test the quick brown fox example."""
    reference_text = "The quick brown fox jumps over the lazy dog."

    print("=" * 70)
    print("Testing Word-to-Phoneme Alignment")
    print("=" * 70)
    print(f"\nInput text: {reference_text}\n")

    # Generate phonemes using gruut
    lexicon, words = generate_reference_phonemes(reference_text, lang="en-us")

    print("Lexicon generated by gruut:")
    print("-" * 70)
    for word, phonemes in lexicon:
        print(f"  {word:12} → /{phonemes}/")
    print()

    # Prepare widget data
    widget_data = prepare_pronunciation_widget_data(reference_text, lexicon)

    print("Widget data prepared:")
    print("-" * 70)
    print(f"Total phoneme string: /{widget_data['phoneme_text']}/")
    print()

    print("Word timings (word → phonemes mapping):")
    print("-" * 70)
    for wt in widget_data["word_timings"]:
        print(f"  {wt['word']:12} → /{wt['phonemes']}/")
    print()

    # Verify alignment
    print("Verification:")
    print("-" * 70)
    assert len(widget_data["word_timings"]) == len(words), \
        f"Mismatch: {len(widget_data['word_timings'])} word_timings vs {len(words)} words"

    for i, (wt, (expected_word, expected_phon)) in enumerate(zip(widget_data["word_timings"], lexicon)):
        assert wt["word"] == expected_word, \
            f"Word mismatch at index {i}: {wt['word']} != {expected_word}"
        assert wt["phonemes"] == expected_phon, \
            f"Phoneme mismatch at index {i}: {wt['phonemes']} != {expected_phon}"

    print("✓ All word-to-phoneme mappings are correct!")
    print("✓ Alignment preserved correctly!")
    print()

    print("Expected output in widget:")
    print("-" * 70)
    print("Word        | IPA Phonemes")
    print("-" * 70)
    for wt in widget_data["word_timings"]:
        print(f"{wt['word']:12} | /{wt['phonemes']}/")
    print()

    print("=" * 70)
    print("SUCCESS: Word-phoneme alignment working correctly!")
    print("=" * 70)


if __name__ == "__main__":
    test_alignment()
